# Generated by Django 2.1.11 on 2019-08-10 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='created_at',
            new_name='time_create',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='updated_at',
            new_name='time_mod',
        ),
    ]
