# Generated by Django 2.1.11 on 2019-08-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20190812_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='note',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='wish',
            name='bid',
            field=models.CharField(max_length=255),
        ),
    ]
